service: aws-notes
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: GET
  postNote:
    handler: functions/postNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: POST
  editNote:
    handler: functions/editNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: PUT
  deleteNote:
    handler: functions/deleteNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: DELETE
  trashBin:
    handler: functions/trashBin/index.handler
    events:
    - httpApi:
        path: '/api/trash'
        method: GET
  recoverNote:
    handler: functions/recoverNote/index.handler
    events:
    - httpApi:
        path: '/api/restore'
        method: POST
  login:
    handler: functions/login/index.handler
    events:
    - httpApi:
        path: '/api/user/login'
        method: POST
  signUp:
    handler: functions/signUp/index.handler
    events:
    - httpApi:
        path: '/api/user/signup'
        method: POST

resources:
  Resources:
    noteDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: note-db # Database table name
        AttributeDefinitions:
          - AttributeName: id # database item id
            AttributeType: S # String
        KeySchema:
          - AttributeName: id # database key id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


