
Resources:
  PostNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/postNote/index.handler
      Runtime: nodejs14.x
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /postNote
            Method: post